"""empty message

Revision ID: 1ad93ec19fba
Revises: 5fd39acf7644
Create Date: 2021-12-21 23:00:19.391696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ad93ec19fba'
down_revision = '5fd39acf7644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tokens',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('jti', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('token_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('user_identity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('expires', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
