"""empty message

Revision ID: 5fd39acf7644
Revises: cdcee89db749
Create Date: 2021-12-21 02:28:28.795765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd39acf7644'
down_revision = 'cdcee89db749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'admins', ['email'])
    op.create_unique_constraint(None, 'admins', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
